name: AndroidBuild
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1

      - name: Build with Gradle
        uses: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.1.7
        with:
          name: android_smart_tv.apk
          path: app/build/outputs/apk/app-debug.apk